title: Vy Tran # your name (or website title) here
logo: "/images/vytran.png?raw=true" # your photo (or logo) here
description: >
I am a doctoral student at Johns Hopkins University.
<br>
I have interdisciplinary training in cancer biology, 
<br>
public health, and programming. Passionate about
<br>
healthcare and data science, and skilled in
<br>
quantitativedata analysis with large genomic data sets, 
<br>
electronic health records, network analysis, and systems biology.
<br>
Highly effective academic writer and presenter.
<br><br>
<a href="https://www.linkedin.com/in/example/">LinkedIn</a> 
|
<a href="https://scholar.google.com/citations?hl=en&user=wCOh7Y0AAAAJ&scilu=&scisig=AMD79ooAAAAAXc3Gc39xZbw0IEpKjVBZ4cRYTq9tIbB8&gmla=AJsN-F5BbxaVRjIQXGPVD5P45x9dFFObIcam4QZ7Qar1vjXeDXuLrPzHzaH05My6hpD3IG7uFtSL-FF5NywWRt5NpqOdSGZiyrgl7NaR9yp9AEvS7iQJ6o0&sciund=16552258558291886132">Google Scholar</a> 
|
<a href="https://github.com/vy-p-tran">Github</a> 
theme: jekyll-theme-minimal


