title:               Vy Tran # your name (or website title) here
logo: "/images/vytran.png?raw=true" # your photo (or logo) here
description: I am a young bioinformatician with interdisciplinary training in cancer biology, public health, and programming. Passionate about healthcare and data science, and skilled 
  in quantitative data analysis with large genomic data sets, electronic health records, network analysis, and systems biology. Highly effective academic writer and presenter.
  <br><br>


