title: Vy Tran # your name (or website title) here
logo: "/images/vytran.png?raw=true" # your photo (or logo) here
description: >
I am a young bioinformatician with interdisciplinary training in cancer biology, public health, and programming. Passionate about healthcare and data science, and skilled 
in quantitative data analysis with large genomic data sets, electronic health records, network analysis, and systems biology. Highly effective academic writer and presenter.
<br><br>
<a href="https://www.linkedin.com/in/example/">LinkedIn</a> 
<br>
<a href="https://scholar.google.com/citations?hl=en&user=wCOh7Y0AAAAJ&scilu=&scisig=AMD79ooAAAAAXc3Gc39xZbw0IEpKjVBZ4cRYTq9tIbB8&gmla=AJsN-F5BbxaVRjIQXGPVD5P45x9dFFObIcam4QZ7Qar1vjXeDXuLrPzHzaH05My6hpD3IG7uFtSL-FF5NywWRt5NpqOdSGZiyrgl7NaR9yp9AEvS7iQJ6o0&sciund=16552258558291886132">Google Scholar</a> 
title: John Doe # your name (or website title) here  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
