title:               Vy Tran # your name (or website title) here
logo: "/images/Vy Tran.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A young bioinformatician with interdisciplinary training in toxicology, cancer biology, statistical and programming skills. Passionate about cancer research and data science, and experienced in using multi-dimensional data to uncover molecular mechanisms linking genotype to cancer phenotype. Skilled in quantitative data analysis with large genomic data sets, network analysis, and systems biology. Proficient at R statistical and programming software, academic writing and presentation. 
  <br><br>
  
  <br><br>
  <a href="https://www.linkedin.com/in/vy-tran-01/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
