title:               Vy Tran # your name (or website title) here
logo: "/images/Vy Tran.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD Student, Johns Hopkins University
  <br><br>
  I am a young bioinformatician with interdisciplinary training <br>
  in cancer biology, public health, and programming.<br>
  Passionate about healthcare and data science, and skilled <br>
  in quantitative data analysis with large genomic data sets,<br>
  electronic health records, network analysis, and systems biology.<br>
  Highly effective academic writer and presenter.
  <br><br>
  <a href="https://www.linkedin.com/in/vy-tran-01/">LinkedIn
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
